Repository privateerproj/privateer-sdk, pull requests merged in 2025-08, with the labels that each got.

#91 chore: use gemara v0.3.10 in place of sci
  go.mod
  go.sum
  pluginkit/evaluation_orchestrator.go
  pluginkit/evaluation_orchestrator_test.go
  pluginkit/evaluation_suite.go
  pluginkit/evaluation_suite_test.go
  pluginkit/test_data.go
Labels: maintenance

#94 feat: Add recommendation to assessment result (upgrade Gemara 0.4.2)
  config/config.go
  go.mod
  go.sum
  pluginkit/evaluation_orchestrator.go
  pluginkit/evaluation_orchestrator_test.go
  pluginkit/evaluation_suite.go
Labels: feature

#97 fix: field names to pascal-case with yaml tags for snake-case
  pluginkit/evaluation_orchestrator.go
  pluginkit/evaluation_orchestrator_test.go
  pluginkit/evaluation_suite.go
  pluginkit/evaluation_suite_test.go
Labels: fix
