Repository privateerproj/privateer-sdk, pull requests merged in 2025-09, with the labels that each got.

#106 fix: ensure we're not persisting credentials after checkouts
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: fix

#103 chore: upgrade gemara to v0.7.0
  go.mod
  go.sum
Labels: maintenance

#108 fix(ci): Update dependabot.yml
  .github/dependabot.yml
Labels: fix

#109 fix(docs): Update README to reflect plugin terminology
  README.md
Labels: fix

#110 fix: CODEOWNERS oss team
  .github/CODEOWNERS
Labels: fix

#111 fix: update Dependabot labels
  .github/dependabot.yml
Labels: fix

#113 fix: logging of authn/credential vars
  config/config.go
Labels: fix

#112 chore(deps): upgrade to gemara v0.9.0
  go.mod
  go.sum
  pluginkit/evaluation_suite.go
Labels: maintenance

#119 feat: Add support for SARIF output format
  Makefile
  config/config.go
  go.mod
  go.sum
  pluginkit/evaluation_orchestrator.go
  pluginkit/evaluation_orchestrator_test.go
  pluginkit/evaluation_suite.go
  pluginkit/evaluation_suite_test.go
Labels: feature
