Repository privateerproj/privateer-sdk, pull requests merged in 2025-01, with the labels that each got.

#43 feat: add release, auto labeler, pr-title reusable github actions
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: feature, release

#44 fix: release action config file name misspelling
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
Labels: fix, release

#47 chore: minor improvement to logging output
  pluginkit/test_suite.go
Labels: maintenance

#48 feat: added flag to disable file outputs
  .github/workflows/ci.yml
  command/command.go
  config/config.go
  pluginkit/vessel.go
Labels: feature

#52 fix: CODEOWNERS
  .github/CODEOWNERS
Labels: fix

#54 chore: revert ReadConfig function
  command/command.go
  config/config.go
  pluginkit/vessel.go
Labels: maintenance, release

#55 fix: iterative fix for multi-layered bugs in -c
  command/command.go
Labels: fix, release

#56 ci: bug fixes should update semver patch not minor
  .github/release-drafter.yml
Labels: automation

#50 feat: designate output type
  command/command.go
  config/config.go
  config/config_test.go
  pluginkit/armory.go
  pluginkit/change.go
  pluginkit/test.go
  pluginkit/test_set.go
  pluginkit/test_suite.go
  pluginkit/vessel.go
Labels: feature

#57 ci: update labels that trigger semver changes
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: automation, maintenance

#61 feat: added handling for all plugin command functionality
  command/base.go
  command/plugin.go
  pluginkit/vessel.go
Labels: feature, release
