Repository privateerproj/privateer-sdk, pull requests merged in 2025-03, with the labels that each got.

#70 feat: contributing common structures upstream to SCI
  .github/workflows/ci.yml
  go.mod
  go.sum
  pluginkit/armory.go
  pluginkit/change.go
  pluginkit/change_test.go
  pluginkit/test.go
  pluginkit/test_set.go
  pluginkit/test_set_test.go
  pluginkit/test_suite.go
  pluginkit/test_suite_test.go
  pluginkit/test_test.go
  pluginkit/vessel.go
  pluginkit/vessel_test.go
Labels: feature

#71 feat: Selectively run assessments based on applicability, and sort into catalogs at the top level
  command/plugin.go
  command/plugin_test.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  pluginkit/armory.go
  pluginkit/errors.go
  pluginkit/evaluation_suite.go
  pluginkit/evaluation_suite_test.go
  pluginkit/test_data.go
  pluginkit/test_suite.go
  pluginkit/test_suite_test.go
  pluginkit/vessel.go
  pluginkit/vessel_test.go
Labels: feature, breaking, major

#73 fix: runtime data loading
  command/plugin_test.go
  config/config_test.go
  go.mod
  go.sum
  pluginkit/errors.go
  pluginkit/evaluation_suite.go
  pluginkit/evaluation_suite_test.go
  pluginkit/test_data.go
  pluginkit/vessel.go
  pluginkit/vessel_test.go
Labels: fix

#75 fix: combos of top and service level vars now work
  config/config.go
  config/config_test.go
Labels: fix

#76 fix: Write Directory flag is needed for Containerization
  command/base.go
Labels: fix

#79 chore: remove go- prefix on make targets
  Makefile
Labels: maintenance

#77 fix: invasive config var will now prevent change.Apply() in plugins
  go.mod
  go.sum
  pluginkit/evaluation_suite.go
  pluginkit/test_data.go
  pluginkit/vessel_test.go
Labels: fix

#83 feat: linting action and fixes
  .github/workflows/lint.yml
  command/plugin.go
  config/config.go
  config/config_test.go
  pluginkit/errors.go
  pluginkit/evaluation_suite.go
  pluginkit/test_data.go
  pluginkit/vessel.go
  pluginkit/vessel_test.go
  utils/utils.go
Labels: feature
